# Python CircleCI 2.0 configuration file
version: 2 # this is CircleCI's version number.
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pipenv shell
            flake8 --statistics
            pytest -v --cov=math_funcs
